# -*- coding: utf-8 -*-
from scrapy.item import Item,Field

class MediaItem(Item):
	page_url=Field()
	title=Field()
	eName=Field()
	otherName=Field()
	adaptor=Field()
	director=Field()
	leader=Field()
	kind=Field()
	language=Field()
	duration=Field()
	story=Field()
	keyWord=Field()
	productPerson=Field()
	dubbing=Field()
	executiver=Field()
	original=Field()
	productColtd=Field()
	productionTime=Field()
	licence=Field()
	registration=Field()
	distributColtd=Field()
	totalNumber=Field()
	updateInfo=Field()
	area=Field()
	source=Field()
	createTime=Field()
	updateTime=Field()
	updator=Field()